# Generated by Django 3.0.7 on 2021-08-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_francois_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainersAndLoser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gainer1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('gainer2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('gainer3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('gainer4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('gainer5', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('loser1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('loser2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('loser3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('loser4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('loser5', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
