# Generated by Django 3.0.7 on 2021-08-05 05:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', multiselectfield.db.fields.MultiSelectField(choices=[('SPY', 'SPY'), ('CMCSA', 'CMCSA'), ('KMI', 'KMI'), ('INTC', 'INTC'), ('MU', 'MU')], max_length=21)),
            ],
        ),
    ]
