# Generated by Django 3.0.7 on 2021-08-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_commoditie_etf_mutualfund_nasdaq_sp500_tsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsx',
            name='exchange',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
