# Generated by Django 3.0.7 on 2021-09-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_tsx_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('exchange', models.CharField(max_length=300)),
            ],
        ),
    ]
