# Generated by Django 3.0.7 on 2021-12-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_profilestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
    ]
